# Generated by Django 4.2.27 on 2025-12-03 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="考试名称")),
                ("batch", models.CharField(max_length=50, verbose_name="考试批次")),
                ("exam_date", models.DateField(verbose_name="考试日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="考试时长(分钟)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("requesting", "请求出题中"),
                            ("submitted", "已提交试卷"),
                            ("approved", "已批准"),
                            ("encrypted", "已加密上链"),
                            ("ready", "待考试"),
                            ("ongoing", "考试中"),
                            ("finished", "已结束"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
                "db_table": "exams",
                "ordering": ["-exam_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="版本号"),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(verbose_name="文件大小(bytes)"),
                ),
                (
                    "file_hash",
                    models.CharField(max_length=128, verbose_name="原始文件哈希"),
                ),
                (
                    "ipfs_hash",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="IPFS哈希(加密后)"
                    ),
                ),
                (
                    "encrypted_key",
                    models.TextField(blank=True, verbose_name="加密的对称密钥(SM4)"),
                ),
                (
                    "encryption_iv",
                    models.CharField(blank=True, max_length=64, verbose_name="加密IV"),
                ),
                (
                    "unlock_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解锁时间"
                    ),
                ),
                (
                    "blockchain_tx_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="区块链交易ID"
                    ),
                ),
                (
                    "block_number",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="区块号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("uploaded", "已上传IPFS"),
                            ("encrypted", "已加密"),
                            ("on_chain", "已上链"),
                            ("selected", "已选定"),
                            ("decrypted", "已解密(考试中)"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "试卷",
                "verbose_name_plural": "试卷",
                "db_table": "exam_papers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="科目名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="科目代码"
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所属院系"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "科目",
                "verbose_name_plural": "科目",
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="PaperAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "上传"),
                            ("encrypt", "加密"),
                            ("chain", "上链"),
                            ("view", "查看"),
                            ("download", "下载"),
                            ("decrypt", "解密"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("details", models.JSONField(default=dict, verbose_name="详细信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="exams.exampaper",
                        verbose_name="试卷",
                    ),
                ),
            ],
            options={
                "verbose_name": "访问日志",
                "verbose_name_plural": "访问日志",
                "db_table": "paper_access_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
