# Generated by Django 4.2.27 on 2025-12-03 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperaccesslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_access_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AddField(
            model_name="exampaper",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="exams.exam",
                verbose_name="考试",
            ),
        ),
        migrations.AddField(
            model_name="exampaper",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_papers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传者",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="assigned_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="指定出题教师",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人(COE)",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="exams.subject",
                verbose_name="科目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exampaper",
            unique_together={("exam", "version")},
        ),
    ]
